# Generated by Django 4.0.5 on 2022-08-03 20:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantHabitaciones', models.IntegerField()),
                ('costoPorNoche', models.FloatField(null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Cabaña',
                'verbose_name_plural': 'Cabañas',
                'ordering': ['-costoPorNoche', '-cantHabitaciones'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ambito', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=13)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='huesped', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Huespedes',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField()),
                ('fechaReserva', models.DateField(auto_now_add=True)),
                ('precioFinal', models.FloatField(null=True)),
                ('cantAdultos', models.PositiveSmallIntegerField(help_text='Cantidad de adultos', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cantMenores', models.PositiveSmallIntegerField(help_text='Cantidad de niños', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('cab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquilinos.cab')),
                ('huesped', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inquilinos.huesped')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
                'permissions': (('puede_registrar_reserva', 'Este usuario puede registrar una reserva.'),),
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField()),
                ('cab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquilinos.cab')),
            ],
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('cab', models.ManyToManyField(to='inquilinos.cab')),
            ],
            options={
                'verbose_name_plural': 'Instalaciones',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='cabs/')),
                ('descripcion', models.CharField(max_length=1000)),
                ('cab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquilinos.cab')),
            ],
        ),
        migrations.CreateModel(
            name='CambioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFin', models.DateField(null=True)),
                ('fechaInicio', models.DateField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquilinos.estado')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquilinos.reserva')),
            ],
        ),
    ]
