# Generated by Django 4.0.5 on 2022-08-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalacion',
            name='baja',
            field=models.BooleanField(default=0),
        ),
    ]
