# Generated by Django 4.0.5 on 2022-09-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0002_instalacion_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='huesped',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
