# Generated by Django 4.0.5 on 2022-09-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0003_huesped_dni_huesped_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='baja',
            field=models.BooleanField(default=0),
        ),
    ]
