# Generated by Django 4.0.5 on 2022-09-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0005_alter_huesped_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='habilitada',
            field=models.BooleanField(default=0),
        ),
    ]
