# Generated by Django 4.0.5 on 2022-09-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0006_cab_habilitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='habilitada',
            field=models.BooleanField(default=1),
        ),
    ]
