# Generated by Django 4.0.5 on 2022-09-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('baja', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
