# Generated by Django 4.0.5 on 2022-09-02 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0002_instalacion_baja'),
        ('propietarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('titulo', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('descuento', models.IntegerField()),
                ('cab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquilinos.cab')),
                ('foto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inquilinos.foto')),
            ],
        ),
    ]
