# Generated by Django 4.0.5 on 2022-09-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0003_promocion_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fechaFin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fechaInicio',
            field=models.DateTimeField(),
        ),
    ]
