# Generated by Django 4.0.5 on 2022-09-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietarios', '0004_alter_promocion_fechafin_alter_promocion_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fechaFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fechaInicio',
            field=models.DateField(),
        ),
    ]
